// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBP.Web.Models.Context;

namespace PBP.Web.Migrations.PartyCost
{
    [DbContext(typeof(PartyCostContext))]
    partial class PartyCostContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PBP.Web.Models.Domain.PartyCost", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Allowance");

                    b.Property<decimal>("CostBase");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("IndividualIncomeTax");

                    b.Property<decimal>("JobAnnuity");

                    b.Property<decimal>("MedicalInsurance");

                    b.Property<decimal>("OldAgeInsurance");

                    b.Property<string>("PartyCostID")
                        .IsRequired();

                    b.Property<string>("PartyMemberID");

                    b.Property<decimal>("Payable");

                    b.Property<decimal>("PerformanceWage");

                    b.Property<decimal>("PostWage");

                    b.Property<decimal>("SalaryRankWage");

                    b.Property<int>("State");

                    b.Property<decimal>("UnemploymentInsurance");

                    b.Property<decimal>("UnionCost");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Guid");

                    b.HasAlternateKey("PartyCostID");

                    b.ToTable("PartyCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
