// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBP.Web.Models.Context;

namespace PBP.Web.Migrations.PartyMember
{
    [DbContext(typeof(PartyMemberContext))]
    [Migration("20190424003805_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PBP.Web.Models.Domain.PartyMember", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime>("FormalDate");

                    b.Property<string>("IDCard");

                    b.Property<string>("Name");

                    b.Property<string>("National");

                    b.Property<string>("OrgID");

                    b.Property<string>("PartyMemberID")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<DateTime>("PrepareDate");

                    b.Property<int>("Sex");

                    b.Property<int>("Stage");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Guid");

                    b.HasAlternateKey("PartyMemberID");

                    b.ToTable("PartyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
